return {
	background = "{background}EE",
	foreground = "{foreground}EE",
	cursor = "{cursor}EE",
	color0 = "{color0}EE",
	color1 = "{color1}EE",
	color2 = "{color2}EE",
	color3 = "{color3}EE",
	color4 = "{color4}EE",
	color5 = "{color5}EE",
	color6 = "{color6}EE",
	color7 = "{color7}EE",
	color8 = "{color8}EE",
	color9 = "{color9}EE",
	color10 = "{color10}EE",
	color11 = "{color11}EE",
	color12 = "{color12}EE",
	color13 = "{color13}EE",
	color14 = "{color14}EE",
	color15 = "{color15}EE",
}
