[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x37\x66ile:///home/kim/sea2tb/Pics/Adult/Video/New%20Download)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x16\0\0\x2#\0\0\x3\xb8\0\0\x4!\0\0\0\x16\0\0\x2#\0\0\x3\xb8\0\0\x4!\0\0\0\0\0\0\0\0\a\x80\0\0\0\x16\0\0\x2#\0\0\x3\xb8\0\0\x4!)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(1916 1002)
pl-dock-status=false
playlist-visible=true
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Playlist]
headerStateV2=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\xff\xff\xff\xff\x1\0\0\0\0\0\0\0\0\0\0\0\r\xec\x1f\0\0\0\n\0\0\0\x3\0\0\0\x64\0\0\0\x6\0\0\0\x64\0\0\0\a\0\0\0\x64\0\0\0\x5\0\0\0\x64\0\0\0\n\0\0\0\x64\0\0\0\v\0\0\0\x64\0\0\0\b\0\0\0\x64\0\0\0\t\0\0\0\x64\0\0\0\f\0\0\0\x64\0\0\0\x2\0\0\0\x64\0\0\x2\xf7\0\0\0\r\x1\x1\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\r\0\0\x2\x43\0\0\0\x1\0\0\0\0\0\0\0P\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\x64)
leftSplitterGeometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xc0\0\0\0\x80\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
splitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xb4\0\0\x1\xa4\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
view-mode=1
zoom=0

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x30\0\0\0\xbe\0\0\x5O\0\0\x3y\0\0\x2\x30\0\0\0\xbe\0\0\x5O\0\0\x3y\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x30\0\0\0\xbe\0\0\x5O\0\0\x3y)

[RecentsMRL]
list=file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Blonde%20solo%20Diana%20Gold%20wearing%20stockings%20playing%20with%20her%20cunt.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Blonde%20cougar%20Ellen%20B.%20likes%20to%20moan%20while%20she%20rubs%20her%20h...%20Any.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Big%20Ass%20Granny%20Gets%20A%20Young%20Cock.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Beautiful%20missionary%20pose%20masturbation%20with%20a%20hot%20blonde%20Iva.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/a.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Amazing%20Sex%20Clip%20Hd%20Exotic%20Show%20-%20OOXXX.com.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Amazing%20homemade%20Compilation%20Vintage%20sex%20clip%20-%20Mature%20Fuck%20Tube.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Amateur%20Redhead%20Slut%20Sucks%20And%20Fucks%20-%20Video%20Free%20Porn%20Videos.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Aged%20White%20Milfs%20-%20Slideshow%205%20Holiday%20Edition.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/0018%20Naked%20Pussies%20of%20Grannies%20and%20Milfs.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/ABXXX%20Sweet%20moms%20Porn%20Video.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/ABMILF%20Hairy%20European%20Grandmas%20Porn%20Video.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/52%20year%20old%20GILF%20Angel%20has%20her%20way%20with%20your%20cock%20-%20Mature%20Fuck.mp4, directory:///home/kim/sea2tb/Pics/Adult/Video/New%20Download, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Stepdad%20couldnt%20resist%20seeing%20his%20stepdaughter%20masturbating%20and.mp4, file:///home/kim/sea2tb/Pics/Adult/Video/New%20Download/Glamour%20sweet%20things%20mother%20video.mp4
times=171775, 0, 1999830, 56900, 0, 161900, 348780, 564523, 0, 0, 0, 133566, 512532, 0, -1, -1

[playlistdialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x16\0\0\0\x16\0\0\x3\xb8\0\0\x2\x14\0\0\0\x16\0\0\0\x16\0\0\x3\xb8\0\0\x2\x14\0\0\0\0\0\0\0\0\a\x80\0\0\0\x16\0\0\0\x16\0\0\x3\xb8\0\0\x2\x14)
