"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color1)\
$os\
$hostname\
[ ](fg:color1 bg:color0)\
$cmd_duration\
(color1)\
$directory\
(bg:color3 fg:color2)\
$git_branch\
$git_status\
[](fg:color3 bg:color4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
[](fg:color4 bg:color5)\
$conda\
[](fg:color5 bg:color1)\
[ ](fg:color1)\
$line_break\
$sudo\
$character"""

palette = "pywal"

right_format = """
"""

continuation_prompt = "[∙](color15) "
scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

[sudo]
style = "bg:color0 fg:color15"
symbol = '🧙 '
disabled = false

[os]
disabled = false
style = "bg:color2 fg:color15"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[hostname]
ssh_only = false
ssh_symbol = "🌐"
style = "bg:color2 fg:color15"
format = '[ $ssh_symbol]($style bold)[$hostname]($style bold)'
disabled = false

[username]
show_always = true
style_user = "bg:color2 fg:color15"
style_root = "bg:#ff0000 fg:color15"
format = '[ $user ]($style)'

[directory]
style = "bg:color2 fg:color15"
format = "[ $path ]($style italic)"
truncation_length = 9
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color3"
format = '[[ $symbol $branch ](fg:color15 bg:color3)]($style)'

[git_status]
style = "bg:color3"
format = '[[( $all_status$ahead_behind )](fg:color15 bg:color3)]($style)'
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](#00ff00)'
renamed = '👅'
deleted = '🗑'

[nodejs]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[c]
symbol = " "
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[rust]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[golang]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[php]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[java]
symbol = " "
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[kotlin]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'

[haskell]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:color15 bg:color4)]($style)'
[python]
symbol = ""
style = "bg:color4"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:color15 bg:color4)]($style)'

[lua]
lua_binary = 'lua'
style = "bg:color4"
format = '[[lua 🌙( $version) ](fg:color15 bg:color4)]($style)'

[docker_context]
symbol = ""
style = "bg:color5"
format = '[[ $symbol( $context) ](fg:color15 bg:color5)]($style)'

[conda]
symbol = "  "
style = "fg:color15 bg:color5"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:color2"
format = '[[  $time ](fg:color15 bg:color2)]($style)'

[line_break]
disabled = false

[character]
format = "$symbol "
disabled = false
success_symbol = '[❯](bold fg:color6)'
error_symbol = '[❯](bold fg:#ff0000)'
vimcmd_symbol = '[❮](bold fg:#00ff00)'
vimcmd_replace_one_symbol = '[❮](bold fg:color15)'
vimcmd_replace_symbol = '[❮](bold fg:color15)'
vimcmd_visual_symbol = '[❮](bold fg:color15)'

[cmd_duration]
show_milliseconds = false
style = "fg:color15"
format = '[ in $duration ]($style bold)'
disabled = false
show_notifications = false
min_time_to_notify = 45000

[palettes.pywal]
color0 = "#090b17"
color1 = "#033162"
color2 = "#003c68"
color3 = "#034b74"
color4 = "#03547e"
color5 = "#0a6689"
color6 = "#1c809a"
color7 = "#8d8f98"
color8 = "#595b6d"
color9 = "#054283"
color10 = "#01508B"
color11 = "#04659B"
color12 = "#0571A8"
color13 = "#0E88B7"
color14 = "#26ABCE"
color15 = "#c1c2c5"
