"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$os\
$hostname\
[](bg:color_bg3 fg:color_bg1)\
$username\
[](bg:color_bg1 fg:color_bg3)\
$directory\
[](fg:color_bg1 bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_purple)\
$lua\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_purple bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_blue)\
$time\
[ ](fg:color_blue)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#48471a'
color_orange = '#963d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#a76901'

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰣇"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[hostname]
ssh_only = false
ssh_symbol = "🌐"
style = "bg:color_bg1 fg:color_fg0"
format = "[ $ssh_symbol$hostname:]($style)"

[username]
show_always = true
style_user = "bg:color_bg3 fg:color_fg0"
style_root = "bg:color_bg3 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_green)]($style)'

[git_status]
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_green)]($style)'

[lua]
symbol = '🌙'
style = "bg:color_purple"
format = '[[ $symbol( $version )](fg:color_fg0 bg:color_purple)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg1)]($style)'

[conda]
style = "bg:color_bg1"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg1)]($style)'

[time]
disabled = false
time_format = "%l:%M"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold fg:color_green)'
error_symbol = '[x](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_blue)'
vimcmd_replace_symbol = '[](bold fg:color_blue)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
